# Generated by Django 3.2.6 on 2021-11-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='slug',
            field=models.SlugField(max_length=254, unique=True),
        ),
    ]
