# Generated by Django 3.2.6 on 2021-10-07 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_comment_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='allowed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
