# Generated by Django 3.2.6 on 2021-10-26 05:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_post_allowed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
