# Generated by Django 3.2.6 on 2021-08-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Others')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='marriage_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_type',
            field=models.SmallIntegerField(choices=[(0, 'Regular'), (1, 'Senior')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='purpose_of_use',
            field=models.TextField(blank=True, null=True),
        ),
    ]
