# Generated by Django 3.2.6 on 2021-09-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_husband_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='example', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userwallet',
            name='slug',
            field=models.SlugField(default='example', unique=True),
            preserve_default=False,
        ),
    ]
