# Generated by Django 3.2.6 on 2021-09-29 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_commentreply'),
        ('users', '0007_auto_20210914_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCostTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cost_transaction_posts', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cost_transaction_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Cost Transaction',
                'verbose_name_plural': 'User Cost Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
