# Generated by Django 3.2.6 on 2021-11-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usercosttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='husband',
            name='slug',
            field=models.SlugField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='slug',
            field=models.SlugField(max_length=254, unique=True),
        ),
    ]
