# Generated by Django 3.2.6 on 2021-09-07 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('point', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Point Plan',
                'verbose_name_plural': 'Point Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pointplan',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0.0)), name='point_plan_price_float_range'),
        ),
    ]
