# Generated by Django 3.2.6 on 2021-09-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointplan',
            name='currency',
            field=models.SmallIntegerField(choices=[(0, 'Yen'), (1, 'Dollar')], default=0),
        ),
    ]
