# Generated by Django 3.2.6 on 2021-09-07 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_pointplan_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatRatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('currency', models.SmallIntegerField(choices=[(0, 'Yen'), (1, 'Dollar')], default=0)),
                ('expiration_cycle', models.SmallIntegerField(choices=[(0, 'Monthly'), (1, 'Yearly'), (2, 'Lifetime')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Flat Rate Plan',
                'verbose_name_plural': 'Flat Rate Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='flatrateplan',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0.0)), name='flat_rate_plan_price_float_range'),
        ),
    ]
