# Generated by Django 3.2.6 on 2021-11-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_userwallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatrateplan',
            name='slug',
            field=models.SlugField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pointplan',
            name='slug',
            field=models.SlugField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userwallettransaction',
            name='slug',
            field=models.SlugField(max_length=254, unique=True),
        ),
    ]
