# Generated by Django 3.2.6 on 2021-11-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_room',
            new_name='room',
        ),
    ]
