# Generated by Django 3.2.6 on 2021-09-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Dashboard', max_length=100, null=True)),
                ('skin', models.CharField(blank=True, choices=[('light-layout', 'Light'), ('bordered-layout', 'Bordered'), ('dark-layout', 'Dark'), ('semi-dark-layout', 'Semi Dark')], default='dark-layout', max_length=100, null=True)),
                ('menu_collapsed', models.BooleanField(default=False)),
                ('layout_width', models.CharField(blank=True, choices=[('full-width', 'Full Width'), ('boxed', 'Boxed')], default='full-width', max_length=100, null=True)),
                ('navbar_color', models.CharField(blank=True, choices=[('inherit', 'Inherit'), ('bg-primary', 'Primary'), ('bg-secondary', 'Secondary'), ('bg-success', 'Success'), ('bg-danger', 'Danger'), ('bg-info', 'Info'), ('bg-warning', 'Warning'), ('bg-dark', 'Dark')], default='inherit', max_length=100, null=True)),
                ('navbar_type', models.CharField(blank=True, choices=[('navbar-floating', 'Floating'), ('navbar-sticky', 'Sticky'), ('navbar-static', 'Static'), ('navbar-hidden', 'Hidden')], default='navbar-floating', max_length=100, null=True)),
                ('footer_type', models.CharField(blank=True, choices=[('footer-fixed', 'Sticky'), ('footer-static', 'Static'), ('footer-hidden', 'Hidden')], default='footer-fixed', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Dashboard Setting',
                'verbose_name_plural': 'Dashboard Settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
