# Generated by Django 3.2.6 on 2021-11-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBStranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_version', models.TextField()),
                ('japanese_version', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BBS Translation',
                'verbose_name_plural': 'BBS Translations',
                'ordering': ['-created_at'],
            },
        ),
    ]
