# Generated by Django 3.2.6 on 2021-11-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_bbstranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsetting',
            name='allow_auto_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bbstranslation',
            name='slug',
            field=models.SlugField(max_length=254, unique=True),
        ),
    ]
