# Generated by Django 3.2.6 on 2021-11-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20211107_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsetting',
            name='allow_translation',
            field=models.BooleanField(default=True),
        ),
    ]
